DROP TABLE IF EXISTS RESERVATIONS;
DROP TABLE IF EXISTS PETS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;

CREATE TABLE ROLES (
    RID VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    UNIDAD VARCHAR(20) NOT NULL CHECK (UNIDAD IN ('OOAD', 'UNIDAD'))
);

INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('CONTROL','CONTROL DEL PROCESO ','OOAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('OPERATIVO','OPERADOR DEL SISTEMA EN OOAD ','OOAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('SECCION','JEFE DE SECCIÓN EN OOAD ','OOAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('OFICINA','JEFE DE OFICINA EN OOAD ','OOAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('DEPARTAMENTO','JEFE DE DEPARTAMENTO EN OOAD ','OOAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('SERVICIO','JEFE DE SERVICIO EN OOAD ','OOAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('OPERATIVO_UNIDAD','OPERADOR DEL SISTEMA EN UNIDAD','UNIDAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('OFICINA_UNIDAD','JEFE DE OFICINA EN UNIDAD','UNIDAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('DEPARTAMENTO_UNIDAD','JEFE DE DEPARTAMENTO EN UNIDAD','UNIDAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('ADMINISTRADOR','ADMINISTRADOR EN UNIDAD','UNIDAD');
INSERT INTO ROLES (RID,NOMBRE,UNIDAD) VALUES ('DIRECTOR','ADMINISTRADOR EN UNIDAD','UNIDAD');


CREATE TABLE USUARIOS (
	MATRICULA VARCHAR(20) PRIMARY KEY,
	PASSWORD VARCHAR(60) NOT NULL,
    NICKNAME: VARCHAR(20) NOT NULL UNIQUE,
    NOMBRE: VARCHAR(50) NOT NULL,
    APELLIDO1: VARCHAR(50) NOT NULL,
    APELLIDO2: VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL UNIQUE
    UNIDAD_TRABAJO VARCHAR(50) NOT NULL,
    SERVICIO VARCHAR(40) NULL,
    DEPARTAMENTO VARCHAR(40) NULL,
    OFICINA VARCHAR(40) NULL,
    SECCION VARCHAR(40) NULL,
    ROLE_ID INT NOT NULL DEFAULT 'OPERATIVO',
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(RID)
);

CREATE TABLE PERFILES (
    PID VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO VARCHAR(20) NOT NULL CHECK (TIPO IN ('CONTENEDOR','PERFIL'))
    TRABAJADORES BOOLEAN NOT NULL DEFAULT FALSE,
    JUBILADOS BOOLEAN NOT NULL DEFAULT FALSE,
    USUARIO_ID VARCHAR(20) NOT NULL,
);

CREATE TABLE USUARIO_PERFILES (
    PID VARCHAR(20) PRIMARY KEY,
    MATRICULA VARCHAR(20) NOT NULL,
    FOREIGN KEY (PID) REFERENCES PERFILES(PID)
    FOREIGN KEY (MATRICULA) REFERENCES USUARIOS(MATRICULA)
);



SELECT * FROM USERS;

-- CREAR VÍA API:
-- admin@admin.com, vet_1@vet.com, client_1@client.com

-- ACTUALIZAR ROLE ADMIN
UPDATE USERS
SET ROLE_ID = 1
WHERE EMAIL = 'admin@admin.com';

-- VIDEO 3 PAGINACIÓN
SELECT * FROM USERS;
SELECT * FROM PETS;

-- verificar que tengas un usuario client y según su uid crear pets
-- CREAR PETS 21 PETS CON OWNER 3 (siempre y cuando exista el owner 3)
INSERT INTO pets (NAME, SPECIES, BREED, OWNER) VALUES
('Firulais', 'Perro', 'Labrador', 3),
('Mishi', 'Gato', 'Siames', 3),
('Milo', 'Perro', 'Chihuahua', 3),
('Molly', 'Perro', 'Pug', 3),
('Max', 'Perro', 'Pastor Aleman', 3),
('Luna', 'Perro', 'Labrador', 3),
('Bella', 'Perro', 'Labrador', 3),
('Daisy', 'Perro', 'Labrador', 3),
('Lucy', 'Perro', 'Labrador', 3),
('Cooper', 'Perro', 'Labrador', 3),
('Charlie', 'Perro', 'Labrador', 3),
('Rocky', 'Perro', 'Labrador', 3),
('Buddy', 'Perro', 'Labrador', 3),
('Lola', 'Perro', 'Labrador', 3),
('Sadie', 'Perro', 'Labrador', 3),
('Duke', 'Perro', 'Labrador', 3),
('Zoe', 'Perro', 'Labrador', 3),
('Stella', 'Perro', 'Labrador', 3),
('Penny', 'Perro', 'Labrador', 3),
('Ruby', 'Perro', 'Labrador', 3),
('Rosie', 'Perro', 'Labrador', 3);